### ISSUE TITLE
selected line/button colour in midnight-blue(using with kvantum)

### ISSUE THREAD

**Issue by np1729** [Rokin05/midnight-kde#1]
![screenshot_20180428_122454](https://user-images.githubusercontent.com/38804205/39393198-f75b1d62-4adf-11e8-8187-af08b548efbb.png)

**Comment by Rokin05** [comment]
Hello and sorry for the delay, i have not receive any notification from github issue and i have only see now the ticket.

Can you explain little more the problem ?
I have the same look at your screenshot and i'm not sure to understand :x
