### ISSUE TITLE
Why build Kvantum from source for Arch Linux?

### ISSUE THREAD

**Issue by marhkb** [Rokin05/midnight-kde#2]
It's in community:

    community/kvantum-qt5

**Comment by Rokin05** [comment]
Because i think it's new and i'm not h24 on arch repo for spam f5 to check that :)
It's a method like any other, but it's a good new and i will update the readme.

**Comment by Rokin05** [comment]
Done ;)
#1a47711

**Comment by Rokin05** [comment]
i feel so bad with github
